CREATE TABLE SALESMAN(SALESMAN_ID INTEGER PRIMARY KEY,NAME VARCHAR(20) , CITY VARCHAR(20) , COMMISSION VARCHAR(20) );
DESC SALESMAN;
INSERT INTO SALESMAN VALUES(&SALESMAN_ID , '&NAME' , '&CITY' , '&COMMISSION');
SELECT * FROM SALESMAN;S
CREATE TABLE CUSTOMER(CUSTOMER_ID INTEGER PRIMARY KEY , CUST_NAME VARCHAR(20) ,CITY VARCHAR(20) , GRADE INTEGER , SALESMAN_ID REFERENCES SALESMAN(SALESMAN_ID) ON DELETE SET NULL );
INSERT INTO CUSTOMER(&CUSTOMER_ID , 
