CREATE TABLE SALESMAN(SALESMAN_ID INTEGER PRIMARY KEY,NAME VARCHAR(20) , CITY VARCHAR(20) , COMMISSION VARCHAR(20) );
DESC SALESMAN;
INSERT INTO SALESMAN VALUES(&SALESMAN_ID , '&NAME' , '&CITY' , '&COMMISSION');
SELECT * FROM SALESMAN;S
CREATE TABLE CUSTOMER(CUSTOMER_ID INTEGER PRIMARY KEY , CUST_NAME VARCHAR(20) ,CITY VARCHAR(20) , GRADE INTEGER , SALESMAN_ID REFERENCES SALESMAN(SALESMAN_ID) ON DELETE SET NULL );
INSERT INTO CUSTOMER VALUES(&CUSTOMER_ID , '&CUST_NAME' , '&CITY' , &GRADE , &SALESMAN_ID);
CREATE TABLE ORDERS (ORD_NO INTEGER PRIMARY KEY , PURCHASE_AMT NUMBER , ORD_DATE DATE,CUSTOMER_ID REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE SET NULL , SALESMAN_ID REFERENCES SALESMAN(SALESMAN_ID) ON DELETE SET NULL);
INSERT INTO ORDERS VALUES (&ORD_NO , &PURCHASE_AMT,'&ORD_DATE' , &CUSTOMER_ID , &SALESMAN_ID );
