CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE EMPLOYEE(SSN INT PRIMARY KEY , NAME VARCHAR2(20),ADDRESS VARCHAR2(20),GENDER VARCHAR(20) , SALARY INT , SUPER_SSN INT REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE );
CREATE TABLE DEPARTMENT(DNO INT PRIMARY KEY , DNAME VARCHAR2(20) , MGRSSN INT REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE , MGRSTARTDATE INT);
CREATE TABLE DLOCATION(DNO INT REFERENCES DEPARTMENT(DNO) ON DELETE CASCADE , DLOC VARCHAR(20) );
CREATE TABLE PROJECT(PNO INT PRIMARY KEY , PNAME VARCHAR2(20) , PLOCATION VARCHAR2(20) , DNO INT REFERENCES DEPARTMENT(DNO) ON DELETE CASCADE);
CREATE TABLE WORKS_ON (SSN INT REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE  , PNO INT REFERENCES PROJECT(PNO) ON DELETE CASCADE, HOURS INT );

ALTER TABLE EMPLOYEE ADD DNO INT REFERENCES DEPARTMENT(DNO) ON DELETE CASCADE ;


INSERT INTO EMPLOYEE VALUES(&SSN , '&NAME' , '&ADDRESS' , '&GENDER' , &SALARY , &SUPER_SSN );

INSERT INTO DEPARTMENT VALUES(&DNO , '&DNAME' , &MGRSSN , &MGRSTARTDATE);
UPDATE EMPLOYEE SET DNO=3 WHERE SSN=01 ;
UPDATE EMPLOYEE SET DNO=5 WHERE SSN=02 ;
UPDATE EMPLOYEE SET DNO=5 WHERE SSN=03 ;
UPDATE EMPLOYEE SET DNO=3 WHERE SSN=04 ;
UPDATE EMPLOYEE SET DNO=1 WHERE SSN=05 ;

INSERT INTO DLOCATION (&DNO , '&DLOC');
INSERT INTO PROJECT (&PNO , '&PNAME' , '&PLOCATION' , &DNO );
INSERT INTO WORKS_ON (&SSN , &PNO  , &HOURS );


