CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE EMPLOYEE(SSN INT PRIMARY KEY , FNAME VARCHAR2(20), LNAME VARCHAR2(20),ADDRESS VARCHAR2(20),GENDER VARCHAR2(20) , SALARY INT , SUPER_SSN INT REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE );
CREATE TABLE DEPARTMENTS(DNO INT PRIMARY KEY , DNAME VARCHAR2(20) , MGRSSN INT REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE , MGRSTARTDATE DATE);
CREATE TABLE DLOCATION(DNO INT REFERENCES DEPARTMENTS(DNO) ON DELETE CASCADE , DLOC VARCHAR(20) );
CREATE TABLE PROJECT(PNO INT PRIMARY KEY , PNAME VARCHAR2(20) , PLOCATION VARCHAR2(20) , DNO INT REFERENCES DEPARTMENTS(DNO) ON DELETE CASCADE);
CREATE TABLE WORKS_ON (SSN INT REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE  , PNO INT REFERENCES PROJECT(PNO) ON DELETE CASCADE, HOURS INT ); 
INSERT INTO EMPLOYEE VALUES(&SSN , '&FNAME','&LNAME'  , '&ADDRESS' , '&GENDER' , &SALARY , &SUPER_SSN );
INSERT INTO DEPARTMENTS VALUES(&DNO , '&DNAME' , &MGRSSN , '&MGRSTARTDATE');
ALTER TABLE EMPLOYEE ADD DNO INT REFERENCES DEPARTMENTS(DNO) ON DELETE CASCADE ;
UPDATE EMPLOYEE SET DNO=1 WHERE SSN=111 ;
UPDATE EMPLOYEE SET DNO=1 WHERE SSN=222 ;
UPDATE EMPLOYEE SET DNO=1 WHERE SSN=333 ;
UPDATE EMPLOYEE SET DNO=1 WHERE SSN=444 ;
UPDATE EMPLOYEE SET DNO=1 WHERE SSN=555 ;
UPDATE EMPLOYEE SET DNO=1 WHERE SSN=666 ;
UPDATE EMPLOYEE SET DNO=4 WHERE SSN=777 ;
UPDATE EMPLOYEE SET DNO=5 WHERE SSN=888 ;

INSERT INTO DLOCATION VALUES (&DNO , '&DLOC');
INSERT INTO PROJECT VALUES(&PNO , '&PNAME' , '&PLOCATION' , &DNO );
INSERT INTO WORKS_ON VALUES (&SSN , &PNO  , &HOURS );

Q1.
  SELECT DISTINCT P.PNO 
FROM PROJECT P, DEPARTMENTS D, EMPLOYEE E 
WHERE E.DNO = D.DNO 
  AND D.DNO = P.DNO 
  AND (E.LNAME = 'SCOTT' 
       OR D.MGRSSN IN (SELECT SSN FROM EMPLOYEE WHERE LNAME = 'SCOTT'));

Q2.
  SELECT E.SSN, E.FNAME, E.LNAME, 1.1 * E.SALARY AS RAISEDSAL 
FROM EMPLOYEE E, PROJECT P, WORKS_ON W 
WHERE P.PNAME = 'IOT' 
  AND P.PNO = W.PNO 
  AND E.SSN = W.SSN;

Q3.
  SELECT SUM(SALARY) AS SUMSAL, 
       AVG(SALARY) AS AVGSAL, 
       MIN(SALARY) AS MINSAL, 
       MAX(SALARY) AS MAXSAL 
FROM EMPLOYEE E, DEPARTMENTS D 
WHERE E.DNO = D.DNO 
  AND D.DNAME = 'ACCOUNTS';


Q4.
  SELECT E.FNAME, E.LNAME 
FROM EMPLOYEE E 
WHERE NOT EXISTS (
  (SELECT PNO FROM PROJECT WHERE DNO = '5') 
  MINUS 
  (SELECT PNO FROM WORKS_ON WHERE E.SSN = SSN)
);

Q5.
SELECT D.DNO, D.DNAME, E.FNAME, E.LNAME, COUNT(*) AS NOOFEMP 
FROM EMPLOYEE E, DEPARTMENTS D 
WHERE E.DNO = D.DNO 
  AND E.SALARY > 600000 
  AND D.DNO IN (
    SELECT E1.DNO 
    FROM EMPLOYEE E1 
    GROUP BY E1.DNO 
    HAVING COUNT(*) > 5
  ) 
GROUP BY D.DNO, D.DNAME, E.FNAME, E.LNAME;





