CREATE DATABASE AIRLINE;
USE AIRLINE;

CREATE TABLE FLIGHT(FLNO INT PRIMARY KEY , SOURCE VARCHAR2(20) , DESTINATION VARCHAR2(20) , DISTANCE INT , DEPARTS VARCHAR2(20),ARRIVES VARCHAR2(20) , PRICE REAL);
CREATE TABLE AIRCRAFT(AID INT PRIMARY KEY , ANAME VARCHAR2(20) , CRUISINGRANGE INT);
CREATE TABLE EMPLOYEE (EID INT PRIMARY KEY , ENAME VARCHAR2(20) , SALARY INT );
CREATE TABLE CERTIFIED (EID INT REFERENCES EMPLOYEE(EID) ON DELETE CASCADE , AID REFERENCES AIRCRAFT(AID) ON DELETE CASCADE );

