CREATE DATABASE AIRLINE;
USE AIRLINE;

CREATE TABLE FLIGHT(FLNO INT PRIMARY KEY , SOURCE VARCHAR2(20) , DESTINATION VARCHAR2(20) , DISTANCE INT , DEPARTS VARCHAR2(20),ARRIVES VARCHAR2(20) , PRICE REAL);
CREATE TABLE AIRCRAFT(AID INT PRIMARY KEY , ANAME VARCHAR2(20) , CRUISINGRANGE INT);
CREATE TABLE EMPLOYEES (EID INT PRIMARY KEY , ENAME VARCHAR2(20) , SALARY INT );
CREATE TABLE CERTIFIED (EID INT REFERENCES EMPLOYEES(EID) ON DELETE CASCADE , AID INT REFERENCES AIRCRAFT(AID) ON DELETE CASCADE );

INSERT INTO FLIGHT VALUES(&FLNO , '&SOURCE' , '&DESTINATION' ,&DISTANCE , '&DEPARTS' , '&ARRIVES' , &PRICE);
INSERT INTO  AIRCRAFT VALUES(&AID , '&ANAME' , &CRUISINGRANGE );
INSERT INTO EMPLOYEES VALUES(&EID , '&ENAME' , &SALARY );
INSERT INTO CERTIFIED VALUES (&EID , &AID);

Q1.
SELECT ANAME 
FROM AIRCRAFT A, EMPLOYEES E, CERTIFIED C 
WHERE A.AID = C.AID 
  AND E.EID = C.EID 
  AND E.SALARY > 80000;

Q2.
  SELECT E.EID, MAX(CRUISINGRANGE) 
FROM EMPLOYEES E, CERTIFIED C, AIRCRAFT A 
WHERE E.EID = C.EID 
  AND A.AID = C.AID 
GROUP BY E.EID 
HAVING COUNT(*) > 2;

Q3.
  SELECT A.ANAME, AVG(SALARY) 
FROM EMPLOYEES E, CERTIFIED C, AIRCRAFT A 
WHERE C.EID = E.EID 
  AND A.AID = C.AID 
  AND A.CRUISINGRANGE > 1000 
GROUP BY A.ANAME;

Q4.
  (SELECT ENAME 
 FROM EMPLOYEES E, CERTIFIED C 
 WHERE C.AID IN (
   SELECT A.AID 
   FROM AIRCRAFT A, CERTIFIED C 
   WHERE A.AID NOT IN (
     SELECT AID 
     FROM AIRCRAFT 
     WHERE ANAME = 'BOEING' OR CRUISINGRANGE = 3000
   ) 
   GROUP BY A.AID
 ) 
 AND E.EID = C.EID)
MINUS
(SELECT ENAME 
 FROM EMPLOYEES E, CERTIFIED C 
 WHERE C.AID IN (
   SELECT A.AID 
   FROM AIRCRAFT A, CERTIFIED C 
   WHERE A.AID IN (
     SELECT AID 
     FROM AIRCRAFT 
     WHERE ANAME = 'BOEING'
   ) 
   GROUP BY A.AID
 ) 
 AND E.EID = C.EID);

5Q.
  SELECT EID, ENAME, SALARY 
FROM EMPLOYEES 
WHERE SALARY > (
  SELECT AVG(SALARY) 
  FROM EMPLOYEES
) 
AND EID NOT IN (
  SELECT EID 
  FROM CERTIFIED
);








