CREATE DATABASE AIRLINE;
USE AIRLINE;

CREATE TABLE FLIGHT(FLNO INT PRIMARY KEY , SOURCE VARCHAR2(20) , DESTINATION VARCHAR2(20) , DISTANCE INT , DEPARTS VARCHAR2(20),ARRIVES VARCHAR2(20) , PRICE REAL);
CREATE TABLE AIRCRAFT(AID INT PRIMARY KEY , ANAME VARCHAR2(20) , CRUISINGRANGE INT);
CREATE TABLE EMPLOYEE (EID INT PRIMARY KEY , ENAME VARCHAR2(20) , SALARY INT );
CREATE TABLE CERTIFIED (EID INT REFERENCES EMPLOYEE(EID) ON DELETE CASCADE , AID INT REFERENCES AIRCRAFT(AID) ON DELETE CASCADE );

INSERT INTO FLIGHT VALUES(&FLNO , '&SOURCE' , '&DESTINATION' ,&DISTANCE , '&DEPARTS' , '&ARRIVES' , &PRICE);
INSERT INTO  AIRCRAFT VALUES(&AID , '&ANAME' , &CRUISINGRANGE );
INSERT INTO EMPLOYEE VALUES(&EID , '&ENAME' , &SALARY );
INSERT INTO CERTIFIED VALUES (&EID , &AID);



