###University Database
CREATE TABLE STUDENT(SNUM INT PRIMARY KEY,SNAME VARCHAR(20),MAJOR VARCHAR(20),LEV VARCHAR(20),AGE INT);
CREATE TABLE FACULTY(FID INT PRIMARY KEY,FNAME VARCHAR(20),DEPTID INT);
CREATE TABLE CLASS(CNAME VARCHAR(20) PRIMARY KEY , MEETSAT VARCHAR(20),ROOM VARCHAR(20),FID REFERENCES FACULTY(FID) ON DELETE SET NULL);
CREATE TABLE ENROLLED(SNUM REFERENCES STUDENT(SNUM),CNAME REFERENCES CLASS(CNAME));

INSERT INTO STUDENT VALUES(&SNUM,'&SNAME','&MAJOR','&LEV',&AGE);
INSERT INTO FACULTY VALUES(&FID,'&FNAME',&DEPTID);
INSERT INTO CLASS VALUES('&CNAME','&MEETSATA','&ROOM',&FID);
INSERT INTO ENROLLED VALUES(&SNUM,'&CNAME');
