###University Database
CREATE TABLE STUDENT1(SNUM INT PRIMARY KEY,SNAME VARCHAR(20),MAJOR VARCHAR(20),LEV VARCHAR(20),AGE INT);
CREATE TABLE FACULTY(FID INT PRIMARY KEY,FNAME VARCHAR(20),DEPTID INT);
CREATE TABLE CLASS(CNAME VARCHAR(20) PRIMARY KEY , MEETSAT VARCHAR(20),ROOM VARCHAR(20),FID REFERENCES FACULTY(FID) ON DELETE SET NULL);
CREATE TABLE ENROLLED(SNUM REFERENCES STUDENT1(SNUM),CNAME REFERENCES CLASS(CNAME));

INSERT INTO STUDENT1 VALUES(&SNUM,'&SNAME','&MAJOR','&LEV',&AGE);
INSERT INTO FACULTY VALUES(&FID,'&FNAME',&DEPTID);
INSERT INTO CLASS VALUES('&CNAME','&MEETSATA','&ROOM',&FID);
INSERT INTO ENROLLED VALUES(&SNUM,'&CNAME');

1Q.
  SELECT DISTINCT S.SNUM, S.SNAME 
FROM STUDENT1 S, CLASS C, ENROLLED E, FACULTY F 
WHERE S.SNUM = E.SNUM 
  AND E.CNAME = C.CNAME 
  AND C.FID = F.FID 
  AND F.FNAME = 'RAKESH' 
  AND S.LEV = 'JR' 
ORDER BY S.SNUM;

2Q.
  SELECT MAX(S.AGE) AS AGE 
FROM STUDENT1 S 
WHERE (S.MAJOR = 'HISTORY') 
   OR S.SNUM IN (
     SELECT E.SNUM 
     FROM CLASS C, ENROLLED E, FACULTY F 
     WHERE E.CNAME = C.CNAME 
       AND C.FID = F.FID 
       AND F.FNAME = 'RAVI'
   );

3Q.
  SELECT DISTINCT S.SNAME 
FROM STUDENT1 S 
WHERE S.SNUM IN (
  SELECT E1.SNUM 
  FROM ENROLLED E1, ENROLLED E2, CLASS C1, CLASS C2 
  WHERE E1.SNUM = E2.SNUM 
    AND E1.CNAME <> E2.CNAME 
    AND E1.CNAME = C1.CNAME 
    AND E2.CNAME = C2.CNAME 
    AND C1.MEETSAT = C2.MEETSAT
);

4Q.
  SELECT DISTINCT F.FNAME, COUNT(*) AS COURSECOUNT 
FROM CLASS C, FACULTY F 
WHERE C.FID NOT IN (
  SELECT FID 
  FROM CLASS 
  WHERE ROOM IN (
    SELECT ROOM 
    FROM CLASS 
    WHERE ROOM != 'R128'
  )
) 
AND C.FID = F.FID 
GROUP BY F.FNAME;

5Q.
  CREATE VIEW StudentCourseDetails AS 
SELECT S.SNAME, S.SNUM, C.CNAME 
FROM STUDENT1 S 
JOIN ENROLLED E ON S.SNUM = E.SNUM 
JOIN CLASS C ON E.CNAME = C.CNAME;


